#remember to open the server, Tim
library(RSelenium)
startServer()
remDr <- remoteDriver(remoteServerAddr = "localhost" , port = 4444, browserName = "firefox")
remDr$open()
remDr$navigate("https://www.votebuilder.com")
option1 <- remDr$findElement(using = 'xpath', "//*[@id='TextBoxUserName']")
option1$sendKeysToElement(list('flcc.tphan'))
option2 <- remDr$findElement(using = 'xpath', "//*[@id='TextBoxPassword']")
option2$sendKeysToElement(list('number99'))
option3 <- remDr$findElement(using = 'xpath',"//*[@id='ctl00_ContentPlaceHolderVANPage_ButtonLogin']")
option3$clickElement()
option4<- remDr$findElement(using = 'css', "div.pin-row:nth-child(3) > div:nth-child(3) > div:nth-child(1) > span:nth-child(2)")
a<- unlist(option4$getElementText())
option5<- remDr$findElement(using = 'css', "div.pin-row:nth-child(2) > div:nth-child(2) > div:nth-child(1) > span:nth-child(2)")
b<- unlist(option5$getElementText())
option6<- remDr$findElement(using = 'css', "div.pin-row:nth-child(1) > div:nth-child(1) > div:nth-child(1) > span:nth-child(2)")
c<- unlist(option6$getElementText())
option8<- remDr$findElement(using = 'css', "div.pin-row:nth-child(2) > div:nth-child(3) > div:nth-child(1) > span:nth-child(2)")
d<- unlist(option8$getElementText())
pin<- paste(a,b,c,d, sep='',collapse = '')
option9 <- remDr$findElement(using = 'xpath',"//*[@id='ctl00_ContentPlaceHolderVANPage_VANDetailsItemPIN_VANInputItemDetailsItemPINCode_PINCode']")
option9$sendKeysToElement(list(pin))
option10 <- remDr$findElement(using = 'xpath',"//*[@id='ctl00_ContentPlaceHolderVANPage_ButtonNarrowSubmit']")
option10$clickElement()

